/* Generated By:JavaCC: Do not edit this line. MALanguageTreeConstants.java Version 5.0 */
public interface MALanguageTreeConstants
{
  public int JJTPRINCIPAL = 0;
  public int JJTCOMANDOS = 1;
  public int JJTFUNCTION = 2;
  public int JJTSTMT = 3;
  public int JJTCONDICIONAL = 4;
  public int JJTREPETICAO = 5;
  public int JJTEXPRESSAO = 6;
  public int JJTDECLARACAOVARIAVEL = 7;
  public int JJTSTRING = 8;
  public int JJTNUMERO = 9;
  public int JJTBOOL = 10;
  public int JJTDADO = 11;
  public int JJTTIPODADO = 12;


  public String[] jjtNodeName = {
    "principal",
    "comandos",
    "function",
    "stmt",
    "condicional",
    "repeticao",
    "expressao",
    "declaracaoVariavel",
    "string",
    "numero",
    "bool",
    "dado",
    "tipoDado",
  };
}
/* JavaCC - OriginalChecksum=d9b7c7266225be5f1188616f20d34de3 (do not edit this line) */
