/* Generated By:JJTree&JavaCC: Do not edit this line. MALanguageConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MALanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 5;
  /** RegularExpression Id. */
  int FIMPROGRAMA = 6;
  /** RegularExpression Id. */
  int INICIOBLOCO = 7;
  /** RegularExpression Id. */
  int FIMBLOCO = 8;
  /** RegularExpression Id. */
  int REAL = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int INTEIRO = 11;
  /** RegularExpression Id. */
  int LETRA = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 14;
  /** RegularExpression Id. */
  int DIGITO = 15;
  /** RegularExpression Id. */
  int CARACTERE = 16;
  /** RegularExpression Id. */
  int ATRIBUICAO = 17;
  /** RegularExpression Id. */
  int SEPARADOR = 18;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int LPAR = 22;
  /** RegularExpression Id. */
  int RPAR = 23;
  /** RegularExpression Id. */
  int DECIMAL = 24;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 25;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int FUNCTION = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int ISTRING = 30;
  /** RegularExpression Id. */
  int INTERRUPCAO = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<INICIOPROGRAMA>",
    "<FIMPROGRAMA>",
    "\"smaaash\"",
    "<FIMBLOCO>",
    "\"yandere\"",
    "\"kuudere\"",
    "\"deredere\"",
    "\"tsuntsun\"",
    "\"tsundere\"",
    "\"desu\"",
    "<DIGITO>",
    "<CARACTERE>",
    "\"=\"",
    "\",\"",
    "<IDENTIFICADOR>",
    "\"moemoe\"",
    "\"kyun\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "<OPERADOR_LOGICO>",
    "<OPERADOR_ARITMETICO>",
    "\"steins\"",
    "<FUNCTION>",
    "\"ayaya\"",
    "\"\\\'\"",
    "\"yamero\"",
    "\"redonda\"",
    "\"plana\"",
  };

}
